project:
  type: website

website:
  title: "Women in Logic"
  favicon: assets/favicon.png

  navbar:
    search: true
    logo: assets/logo_white.png
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: workshops/index.qmd
        text: Workshops
      - href: governance/index.qmd
        text: Governance
      - href: data/index.qmd
        text: Data
      - href: contact/index.qmd
        text: Get Involved
    tools:
      - icon: twitter
        href: https://twitter.com/womeninlogic1
      - icon: facebook
        href: https://www.facebook.com/groups/WomenInLogic

  back-to-top-navigation: false
  page-footer:
    center: |
      Contact us by email: [`wil.info22@gmail.com`](mailto:wil.info22@gmail.com)

format:
  html:
    theme: pulse
    css: assets/styles.css
    toc: false
    anchor-sections: false
